# Generated by Django 5.1.1 on 2024-09-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_blogpost_blog_picture_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_picture',
        ),
    ]
